export enum PaymentType {
  CARD = 'CARD',
  EWALLET = 'EWALLET',
  DIRECT_DEBIT = 'DIRECT_DEBIT',
  OVER_THE_COUNTER = 'OVER_THE_COUNTER',
  QR_CODE = 'QR_CODE',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
}
